#!/bin/sh
cat frame.head > index.html
cat index.text >> index.html
cat frame.tail >> index.html

cat frame.head > vision.html
cat vision.text >> vision.html
cat frame.tail >> vision.html

cat frame.head > screenshots.html
cat screenshots.text >> screenshots.html
cat frame.tail >> screenshots.html


cat frame.head > guide.html
cat guide.text >> guide.html
cat frame.tail >> guide.html

cat frame.head > introduction.html
cat introduction.text >> introduction.html
cat frame.tail >> introduction.html

cat frame.head > installation.html
cat installation.text >> installation.html
cat frame.tail >> installation.html

cat frame.head > usage.html
cat usage.text >> usage.html
cat frame.tail >> usage.html

cat frame.head > project.html
cat project.text >> project.html
cat frame.tail >> project.html


cat frame.head > guidelines.html
cat guidelines.text >> guidelines.html
cat frame.tail >> guidelines.html

cat frame.head > development.html
cat development.text >> development.html
cat frame.tail >> development.html

cat frame.head > history.html
cat history.text >> history.html
cat frame.tail >> history.html

cat frame.head > maillist.html
cat maillist.text >> maillist.html
cat frame.tail >> maillist.html

cat frame.head > roadmap.html
cat roadmap.text >> roadmap.html
cat frame.tail >> roadmap.html

cat frame.head > author.html
cat author.text >> author.html
cat frame.tail >> author.html

cat frame.head > download.html
cat download.text >> download.html
cat frame.tail >> download.html

cat frame.head > modes.html
cat modes.text >> modes.html
cat frame.tail >> modes.html

echo "FreeMind website compiled!"